// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface RespImagePiker {
    fileName: string;
    fileSize: number;
    height:   number;
    type:     string;
    uri:      string;
    width:    number;
}
